In [2]:
import numpy as np

x = np.array([
    [0, 1, 3, 4, 0],
    [0, 3, -1, 1, 0]])

w = np.array([
    [2, 1, -1],
    [-1, 2, 3]])

y1 = w * x[:, :3]
y2 = w * x[:, 1:4]
y3 = w * x[:, 2:5]
(y1 + y2 + y3).sum()

13

In [3]:
x[:, :3]

array([[ 0,  1,  3],
       [ 0,  3, -1]])

In [15]:
x_1 = np.array([[7], [-4]])
x_2 = np.array([[0.5], [3]])
x_3 = np.array([[10], [2]])

W_aa = np.array([
                [0, 1, 0],
                [2, 0, -1],
                [0, 1, 3]])
W_ax = np.array([
                [0, 2],
                [1, 0],
                [0, 4]])
b_a = np.array([[-1], [1], [0]])

def relu(x):
  return np.where(x > 0, x, 0)

In [17]:
y1 = W_ax @ x_1 + b_a
y2 = W_aa @ relu(y1) + W_ax @ x_2 + b_a
y2

array([[13. ],
       [ 1.5],
       [20. ]])

In [9]:
a1 = np.array([0.5, 1.0, 0.3, 1.3])
a1.var()

0.15687500000000001

In [7]:
a1.mean()

0.775

In [12]:
(a1 - a1.mean())/((a1.var() + 0.01)**0.5)

array([-0.69431384,  0.56807496, -1.19926937,  1.32550825])

In [10]:
a2 = np.array([[0.5, 1.0, 0.3, 1.3],
              [0.9, 0.2, 0.4, 1.0]])

In [11]:
(a2 - a2.mean())/((a2.var() + 0.01)**0.5)

array([[-0.51639778,  0.77459667, -1.03279556,  1.54919334],
       [ 0.51639778, -1.29099445, -0.77459667,  0.77459667]])

In [14]:
a2.var()

0.14